name: hisn_almuslim
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  adhan: ^2.0.0+1
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  audioplayers: ^6.7.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.1.0
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.2
  flutter_islamic_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.2
  flutter_screenutil: ^5.9.3
  flutter_timezone: ^5.1.0
  gap: ^3.0.1
  geolocator: ^14.0.2
  get_it: ^9.2.1
  hijri: ^3.0.0
  http: ^1.6.0
  intl: ^0.20.2
  introduction_screen: ^4.0.0
  just_audio: ^0.10.6
  lottie: ^3.3.2
  path_provider: ^2.1.5
  pdf: ^3.12.0
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  timezone: ^0.10.1
  youtube_player_iframe: ^6.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/loogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/loogo.png"
  min_sdk_android: 21


flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/questions/
    - assets/icons/
    - assets/json/
    - assets/hadith.json
    - assets/json/daily_content.json
    - assets/questions/database.json
 

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf

    - family: Amiri Quran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

    - family: Uthmani
      fonts:
        - asset: assets/fonts/UthmanicHafs.ttf

    - family: Al mushaf
      fonts:
        - asset: assets/fonts/almushaf-١.ttf

    - family: Noon
      fonts:
        - asset: assets/fonts/ArbFONTS-Noon.ttf

    - family: AlQuranAlkareem
      fonts:
        - asset: assets/fonts/AlQuranAlKareem.ttf

    - family: AlqalamQuranMajeed2
      fonts:
        - asset: assets/fonts/Al_Qalam_Quran_Majeed2.ttf

    - family: QuranFont
      fonts:
        - asset: assets/fonts/uthmanic_hafs.otf